export { default as Onboarding} from './Onboarding'
export { default as Home} from './Home'
export { default as Search} from './Search'
export {default as Categorie} from './Categorie'
export {default as Area} from './Area'
export {default as MealInfo} from './MealInfo'